site_name: MkDocs+
site_description: Examples of integrating MkDocs with 3rd Party Libraries.
site_author: Bruce Marriner
site_url: http://bwmarrin.github.io/MkDocsPlus/

repo_url: https://github.com/bwmarrin/MkDocsPlus

extra_javascript: []
extra_css: []

dev_addr: 0.0.0.0:8000

markdown_extensions:
      - fontawesome_markdown

theme: readthedocs

pages:
    - 'Home': 'index.md'        
    - 'flowchart.js' : 'flowchartjs/index.md'
    - 'js-sequence-diagrams' : 'js-sequence-diagrams/index.md'
    - 'DataTables' : 'datatables/index.md'  
    - 'mermaid' : 'mermaid/index.md' 
    - 'Chartist.js' : 'chartistjs/index.md' 
    - 'Chart.js' : 'chartjs/index.md'  
    - 'Font Awesome' : 'fontawesome/index.md'
